### ISSUE TITLE
Nonce field should not exist for adding existing "main" feed

### ISSUE THREAD

**Issue by staltz** [ssbc/ssb-meta-feeds-spec#22]
In [Existing SSB Identity](https://github.com/ssb-ngi-pointer/ssb-meta-feed-spec#existing-ssb-identity) case, we have

```
{
  "type" => "metafeed/add",
  "feedpurpose" => "main",
  "subfeed" => (BFE-encoded feed ID for the 'main' feed),
  "metafeed" => (BFE-encoded Bendy Butt feed ID for the meta feed),
  "tangles" => {
    "metafeed" => {
      "root" => (BFE nil),
      "previous" => (BFE nil)
    }
  }
}
```

However, in [New SSB Identity](https://github.com/ssb-ngi-pointer/ssb-meta-feed-spec#new-ssb-identity) we have

```
{
  "type" => "metafeed/add",
  "feedpurpose" => "main",
  "subfeed" => (BFE-encoded feed ID for the 'main' feed),
  "metafeed" => (BFE-encoded Bendy Butt feed ID for the meta feed),
  "nonce" => (bencode byte sequence with 32 random bytes),
  "tangles" => {
    "metafeed" => {
      "root" => null,
      "previous" => null
    }
  }
}
```

Note that in the **second we have nonce** and in the **first case we don't**, but the message type is "metafeed/add" in both cases.

**This is a gotcha**, currently [JS ssb-meta-feeds is wrong](https://github.com/ssb-ngi-pointer/ssb-meta-feeds/blob/ec4824f32f4fab016e6ca81c2e02da83485630b3/messages.js#L57-L58) because it has a nonce for the main feed, which is wrong, because the nonce has nothing to do with deriving the main keys.

cc @arj03 @cryptix 

cc @mycognosist for validation

**Comment by cryptix** [comment]
hm.. removing the nonce sometimes is a bit odd to handle when reconstructing a metafeed, tho.

Like, if i only have the metafeed `secret` but not the existing `secret` what should happen? the _sometimes it's okay not to have a nonce_ feels glitchy and another message type might be clearer. like maybe `"metafeed/add/existing"` and `"metafeed/add/derived"`?

**Comment by staltz** [comment]
> another message type might be clearer.

This is one of the ideas I came up with as well, when in a call with arj. I'm also fine with it.

@arj03 ?

**Comment by arj03** [comment]
I'm good with another type.

**Comment by staltz** [comment]
> maybe `"metafeed/add/existing"` and `"metafeed/add/derived"`

I like this
